In [1]:
import numpy as np
import scipy as sp

In [2]:
pushkin_dataset = "/home/fedor/scicodes/ml/nano-gpt-tutorial/data/Pushkin.txt"

with open(pushkin_dataset, 'r') as t:
    text = t.read()

In [3]:
print("length of the dataset in characters = ", len(text))

length of the dataset in characters =  609236


In [4]:
print(text[:1000])

Перевод

Скажите мне, почему «Похититель»
Освистан партером?
Увы, потому что бедный автор
Похитил его у Мольера.


Перевод

Пою сей бой, в котором Толи одолел,
Где погиб не один воин, где Поль отличился,
Николая Матюрена и прекрасную Нитуш,
Рука которой была трофеем ужасной стычки.



Стихотворения 1813 г



К Наталье

Так и мне узнать случилось,
Что за птица Купидон;
Сердце страстное пленилось;
Признаюсь – и я влюблен!
Пролетело счастья время,
Как, любви не зная бремя,
Я живал да попевал,
Как в театре и на балах,
На гуляньях иль в воксалах
Легким зефиром летал;
Как, смеясь во зло Амуру,
Я писал карикатуру
На любезный женской пол;
Но напрасно я смеялся,
Наконец и сам попался,
Сам, увы! с ума сошел.
Смехи, вольность – всё под лавку
Из Катонов я в отставку,
И теперь я – Селадон!
Миловидной жрицы Тальи
Видел прелести Натальи,
И уж в сердце – Купидон!

Так, Наталья! признаюся,
Я тобою полонен,
В первый раз еще, стыжуся,
В женски прелести влюблен.
Целый день, как ни верчуся
Лишь тобою занят

In [5]:
# For tockenixation -- extract unique charaters
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print("vocabulary size = ", vocab_size)

	
 !"'()*,-.0123456789:;?ABCDEFGHIJKLMNOPRSTVWXZ_abcdefghijklmnopqrstuvwxyz «»АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяё–—„…
vocabulary size =  144


In [6]:
# Tokinizer here

stoi = {ch: i for i,ch in enumerate(chars)}
itos = {i: ch for i,ch in enumerate(chars)}

encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

print(encode("Тестовый текст!"))
print(decode(encode("Тестовый текст!")))

[96, 112, 124, 125, 121, 109, 134, 116, 2, 125, 112, 117, 124, 125, 3]
Тестовый текст!


In [7]:
import torch
torch.tensor(encode("Зима! Очей очарование "), dtype=torch.long)

tensor([ 85, 115, 119, 107,   3,   2,  92, 130, 112, 116,   2, 121, 130, 107,
        123, 121, 109, 107, 120, 115, 112,   2])

In [ ]:
n = int(0.9 * len(data))
train_data = data[:n]
val_data = data[n:]

In [9]:
context_window = 8
train_data[:context_window + 1]

tensor([ 93, 112, 123, 112, 109, 121, 111,   1,   1])

In [10]:
x = train_data[:context_window]
y = train_data[1:context_window + 1]

for t in range(context_window):
    context = x[:t+1]
    target = y[t]
    print(f"When input is {context}, prediction is {target}")

When input is tensor([93]), prediction is 112
When input is tensor([ 93, 112]), prediction is 123
When input is tensor([ 93, 112, 123]), prediction is 112
When input is tensor([ 93, 112, 123, 112]), prediction is 109
When input is tensor([ 93, 112, 123, 112, 109]), prediction is 121
When input is tensor([ 93, 112, 123, 112, 109, 121]), prediction is 111
When input is tensor([ 93, 112, 123, 112, 109, 121, 111]), prediction is 1
When input is tensor([ 93, 112, 123, 112, 109, 121, 111,   1]), prediction is 1


In [26]:
torch.manual_seed(1337)
batch_size = 4
context_window = 10

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - context_window, (batch_size,))
    x = torch.stack([data[i:i+context_window] for i in ix])
    y = torch.stack([data[i+1:i+context_window+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs')
print(xb.shape)
print(xb)
print('targets')
print(yb.shape)
print(yb)

print('==========')

for b in range(batch_size):
    for t in range(context_window):
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"input {decode(context.tolist())} -> target {decode([target.tolist()])}")

inputs
torch.Size([4, 10])
tensor([[129, 134,   9,  75, 141,   1,  91, 112,   2, 109],
        [121, 120, 115,   1,  85, 107, 117, 107, 113, 115],
        [  9,   2, 138,   2, 120, 134, 120, 112,   2, 121],
        [  2, 120, 107,   2, 124, 125, 121, 118,   2, 109]])
targets
torch.Size([4, 10])
tensor([[134,   9,  75, 141,   1,  91, 112,   2, 109, 112],
        [120, 115,   1,  85, 107, 117, 107, 113, 115,   2],
        [  2, 138,   2, 120, 134, 120, 112,   2, 121, 108],
        [120, 107,   2, 124, 125, 121, 118,   2, 109, 107]])
input ц -> target ы
input цы -> target ,
input цы, -> target  
input цы,  -> target —
input цы, — -> target 

input цы, —
 -> target Н
input цы, —
Н -> target е
input цы, —
Не -> target  
input цы, —
Не  -> target в
input цы, —
Не в -> target е
input о -> target н
input он -> target и
input они -> target 

input они
 -> target З
input они
З -> target а
input они
За -> target к
input они
Зак -> target а
input они
Зака -> target ж
input они
Закаж -> target и
in

In [39]:
import torch.nn as nn
from torch.nn import functional as F

class BigramLanguageModel(nn.Module):
    
    def __init__(self, vocab_size):
        super().__init__()
        self.tokent_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets = None):
        logits = self.tokent_embedding_table(idx)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B * T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            logits, _ = self(idx)
            logits = logits[:, -1, :]
            probs = F.softmax(logits, dim=1)
            idx_next = torch.multinomial(probs, num_samples=1)

            idx = torch.cat((idx, idx_next), dim=1)

        return idx
    
m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape, loss)
print(decode(m.generate(torch.ones((1,1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([40, 144]) tensor(5.3851, grad_fn=<NllLossBackward0>)

впР*уB*Н7cСДЯзРзРXА д38ЗЩвqс;iХvКюO6?ФРX(FJz2!уnl5EЦqБЙEИpЯn…юёuРиГu…ШOыB*xH«йьиВ„0*gИщмyРwvDлМН(F"1


In [40]:
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [50]:
batch_size = 32
for steps in range(50000):
    xb, yb = get_batch('train')

    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())

2.6559102535247803


In [52]:
print(decode(m.generate(torch.ones((1,1), dtype=torch.long), max_new_tokens=800)[0].tolist()))


Убнньимои. ны»
Алы бвсамистры Газа. влавя ннальюс гдово
В л, рарира,


Подиберак ечи к пнечеликна пый, в лять
Ропецазеробрья шь.
О гот Счт гити ва т зя(Апомлуму дь ствобой ре
Тос стонилождремой па?

Увридья, б,
И г ховенийне аяль ких жи пружди ра коваиши памосядерурот греги ны
И глы Коя грагодонымголуг неныхи, зри в вя.
Ону пив сишомой,
Одне егатьютвимучала вьны ечумероюм ги, лачтнызвотродрорыемя стречастьнылороговосльстосый уе
Веросё гднунны бомочитьбя,

Тать,
Герве, —
Бе,
Вдекуталаря бых...
"С по коветалушь нифе бесль Ужнннны с
"Тии е кебокир нукугдовоког тниноражапло вьнодулодадитей, идам рырылый ниень нали " "
15 —
На,
И,

Глечепу пой прнапр т,
Гоешь тыев,
Спь, стму я – по ю высадых праскай)
Дльюбуга ищный мовь сеезныбове – викав
Ты
Кусла,

Чташлолое;
Пицес чене съяталицадцвеночая. ещи


In [54]:
B, T, C = 4,8,2
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [55]:
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1]
        xbow[b,t] = torch.mean(xprev,0)

In [65]:
wei = torch.tril(torch.ones(T,T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x
xbow2
torch.allclose(xbow, xbow2)

True

In [72]:
torch.manual_seed(1337)
B,T,C = 4,10,32
x = torch.randn(B,T,C)

head_size = 16
key = nn.Linear(C,head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)

k = key(x)
q = query(x)

wei = q @ k.transpose(-2,-1)

tril = torch.tril(torch.ones(T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
print(out.shape)

torch.Size([4, 10, 16])


In [71]:
wei[0]

tensor([[1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [9.9838e-02, 9.0016e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [5.7673e-02, 7.7964e-02, 8.6436e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [5.5583e-02, 7.2802e-02, 5.9104e-01, 2.8057e-01, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [6.0671e-02, 9.5906e-02, 8.2614e-02, 7.2014e-02, 6.8880e-01, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [6.6740e-02, 4.2319e-01, 7.9927e-02, 1.1937e-01, 2.3870e-01, 7.2077e-02,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [4.4445e-02, 1.8311e-01, 6.2282e-02, 5.1708e-02, 1.8026e-01, 3.9620e-01,
         8.1999e-02, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [9.3262e-03, 3.2994